version: '3'
services:
    spring-demo-db:
        image: postgres:13
        networks:
            - spring-demo-net
        environment: 
            - POSTGRES_PASSWORD=postgres_passwd4
        volumes: 
            - spring-demo-db-vol:/var/lib/postgresql/data
        restart: always

    spring-demo-activemq-artemis:
        build: 
            context: ./docker
            dockerfile: Dockerfile-artemis-centos
        networks: 
            - spring-demo-net
        environment: 
            - ARTEMIS_USER=artemis
            - ARTEMIS_PASSWORD=artemis
        volumes: 
            - './docker/_TMP_/artemis/2.17.0:/opt/activemq-artemis'

    spring-demo:
        build: 
            context: .
            dockerfile: Dockerfile
        networks:
            - spring-demo-net
        ports:
            - 8080:8080
        environment: 
            - DB_URL=jdbc:postgresql://spring-demo-db:5432/postgres
            - DB_USER=postgres
            - DB_PASS=postgres_passwd4
            - ACTIVEMQ_HOST=pring-demo-activemq-artemis
        logging:
            driver: json-file
        restart: always
        depends_on: 
            - spring-demo-db
            - spring-demo-activemq-artemis

networks:
    spring-demo-net:
        driver: bridge
volumes: 
    spring-demo-db-vol: